= Mindfulness & Software Development

There's a lot of talk in the popular media about mindfulness. A http://www.amazon.com/s/ref=sr_nr_n_0?fst=as%3Aoff&rh=n%3A283155%2Ck%3Amindfulness&keywords=mindfulness&ie=UTF8&qid=1453158418&rnid=2941120011[quick search in Amazon's books] will yield you more than sixteen thousand results. What's the big deal, and how does it relate to our practical, real-world endeavor of developing software? 

=== What Is It?
The idea of mindfulness is to get really in touch with what's happening right in front of you. It sounds easy, even obvious, but how often have you found yourself driving down the highway only to be startled by the realization that the car in front of you was stopping. Your eyes were looking at it, but your mind didn't really see it until the alarm went off in your head that you were going to crash, assuming you didn't... you know... crash. Think about a time that someone was speaking to you, or you were reading a book, and you realized you hadn't really understood a word of it for who knows how long.

You were lost in thought.

It might be easier to think of mindfulness as what it's not. It's not getting lost in those thoughts. It's not attaching yourself to ideas rather than present experience. It's not seeing everything going on in abstract terms, each with its own story that can span the past, present, and future. It's not basing your solutions and productivity on those stories.

In short, mindfulness is about seeing things exactly as they are, right now, without unecessary commentary or judgment. Research shows that your visual cortex lights up when you think of a scene just like when you look at one. Your language centers activate when you imagine a conversation just like when you have one. It's just as though you had two projectors shining on the same movie screen with two audio tracks. No wonder we get confused.

=== How Does It Relate to Engineering?
When you're presented with an engineering challenge, you need to face the problem and your options head on with a clear head. You have to hear the description of the problem exactly as it is without assuming, commenting, or judging. Otherwise, you'll limit your options or forego opportunities for no reason other than you're dreaming about a remembered past or an imagined future.

When you first hear about the problem, the voice in your head might wander off and add comentary:

- _"If you want this now, I'll bet you'll want that later, and that *never* works. Forget it."_ 
- _"That's a massive request, I don't know how we'll even get all of that done. Why start?"_
- _"We just adopted a new stack, now we're doing this? They're just going to change everything every week. Managers and shiny objects!"_

Mindfulness says "here's the situation, what are my options, right now, for addressing it". A mindful developer will ask good questions about the actual situation, not assume that it's like that _other_ time she did something _just_ like this. 

She'll gather sufficient information about requirements, constraints, and priorities before falling into memories of similar projects. She'll accept that this moment in time is unique. Everything-- from the problem definition, the context, and the available tools-- is changing constantly.

=== Accepting Change
By staying present with the situation as it is, you can let go of your fear of change by accepting that everything changes, faster every day. If you find yourself https://medium.com/@wob/the-sad-state-of-web-development-1603a861d29f#.grgatx3km[raging against the way things are changing], it's like fighting against the flow of a river with your bare hands. 

When I started working with the Internet, I was paid handsomely to write server-side imagemap handlers in Perl for my clients. There was no Javascript nor CSS. Now, we have single-page app frameworks, schema-less cloud-based databases, and mobile-first development. It's unwise to let your mind grasp on to one stage of the evolution of technology as the "right" or "good" one. It's all a blur of change.

You can accept that and keep learning the way gardeners accept that "garden" is a verb, not a noun. It's never done. Your plants grow, flower, and die. You learn, apply what you've learned, and then replace it with something else that works better. To do that, you need to keep you mind open and fully immersed and aware of the changes as they happen. Don't tie yourself to your technological tomato plant and hope it feeds you forever.

=== How to Develop Mindfulness
The obvious way to develop mindfulness is through practice. Traditional meditation may be the most direct route to that practice, but it isn't the only way. Focus on what is going on in your head during meetings. Are you really listening to every word? Are you running to the closest experience you remember for familiarity and comfort? Are you strategizing about how to make yourself look good in front of your peers?

Watch yourself when you solve problems in design or debugging. Are you assuming this is exactly like something else you've done? It rarely is. Patterns are very useful, but they can also blind you to the particulars of the specific problem you're working on. Do you feel uncomfortable when new technologies come up? Really examine why you feel that way. What if you could add this tool to your toolbox? Could it bring more enjoyment and efficiency to your work?

Every now and then, take a minute just to sit quietly or take a walk, away from your computer and your phone. Really look at where you are, how you feel, what you're thinking. Try to stay present and not get lost in stories about bills you haven't paid, that bug you can't reproduce, or the people you work with. Just for a few minutes, scan your body. How does it feel? Breathe in and out and try to stay with that breath. Feel your feet on the floor, your back against the seat. Listen to the sounds around you without commenting on them. 

=== The Next Steps
Many people perceive a *lack* of mindfulness in their work, they are already on the road to increasing it. Just being aware of your thoughts leads to greater awareness like a snowball rolling down a hill. Don't expect to rid yourself of the daydreams or habituated reactions overnight, but increasing your level of mindfulness is a lifetime pursuit that will pay dividends in greater creativity, productivity, and overall happiness.

